Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Models/Denuncia.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace CanalDenunciaWeb.Models
{
    public class Denuncia
    {
        [Required(ErrorMessage = "Id Denuncia obligatorio")]
        public int idDenuncia { get; set; }
        public int Usuario { get; set; }
        public string Identificador { get; set; }
        public int PermiteModificacion { get; set; }
        public int IdEstadoDenuncia { get; set; }
        public string directorio { get; set; }
        public List<Involucrados> involucrados { get; set; }
        public List<Documentos> documentos { get; set; }
        public Detalle detalles { get; set; }
        public List<Comentarios> comentarios { get; set; }
    }
    public class Involucrados
    {
        [Required(ErrorMessage = "Usuario es obligatorio")]
        public int idUsuario { get; set; }
        [Required(ErrorMessage = "Nombre es obligatorio")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "Sede es obligatorio")]
        public string sede { get; set; }
        [Required(ErrorMessage = "Departamento es obligatorio")]
        public string departamento { get; set; }
        public int tipo { get; set; } //Tipo 0 Comité
    }

    public class Documentos
    {
        public string nombre { get; set; }
        public string extension { get; set; }
        public string ruta { get; set; }
        public HttpPostedFileBase archivo { get; set; }
    }

    public class Detalle
    {
        [Required(ErrorMessage = "Fecha Inicio es obligatorio")]
        public string FechaInicio { get; set; }
        [Required(ErrorMessage = "Fecha Fin es obligatorio")]
        public string FechaFin { get; set; }
        [Required(ErrorMessage = "Tipo Delito es obligatorio")]
        public int IdTipoDelito { get; set; }
        [StringLength(3000, ErrorMessage = "Descripción permite un máximo de {1} caracteres ")]
        public string Comentario { get; set; }
        public string Descripcion { get; set; }
        public int IdDepartamentoSede { get; set; }
        public int IdSede { get; set; }
    }

    public class Comentarios
    {
        public int IdDenunciaComentario { get; set; }
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Comentario { get; set; }
        public string Fecha { get; set; }
    }
}

Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Controllers/DenunciaController.cs
using CanalDenunciaWeb.Attribute;
using CanalDenunciaWeb.Data.Models;
using CanalDenunciaWeb.Data.Package.CorreoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaComentarioPkg;
using CanalDenunciaWeb.Data.Package.DenunciaCorreoAnonimoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaDocumentoHistoricoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaDocumentoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaHistoricoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaInvolucradoHistoricoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaInvolucradoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaOficialCumplimientoPkg;
using CanalDenunciaWeb.Data.Package.DenunciaPkg;
using CanalDenunciaWeb.Data.Package.DepartamentoSedePkg;
using CanalDenunciaWeb.Data.Package.TipoDelitoPkg;
using CanalDenunciaWeb.Data.Package.UsuarioPkg;
using CanalDenunciaWeb.Data.Package.UsuarioRolPkg;
using CanalDenunciaWeb.Helper;
using CanalDenunciaWeb.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CanalDenunciaWeb.Controllers
{
    [LoginAuthenticate]
    public class DenunciaController : Controller
    {
        private UsuarioService usuarioService = new UsuarioService();
        private Util util = new Util();
        private EnvioMail envioMail = new EnvioMail();
        private SesionUsuarioDto sesionUsuario = new SesionUsuarioDto();
        private Combobox combobox = new Combobox();
        private DenunciaService denunciaService = new DenunciaService();
        private DenunciaDocumentoHistoricoService denunciaDocumentoHistoricoService = new DenunciaDocumentoHistoricoService();
        private DepartamentoSedeService departamentoSedeService = new DepartamentoSedeService();
        private DenunciaInvolucradoService denunciaInvolucradoService = new DenunciaInvolucradoService();
        private TipoDelitoService tipoDelitoService = new TipoDelitoService();
        private DenunciaDocumentoService denunciaDocumentoService = new DenunciaDocumentoService();
        private DenunciaComentarioService denunciaComentarioService = new DenunciaComentarioService();
        private CorreoService correoService = new CorreoService();
        private DenunciaHistoricoService denunciaHistoricoService = new DenunciaHistoricoService();
        private DenunciaInvolucradoHistoricoService denunciaInvolucradoHistoricoService = new DenunciaInvolucradoHistoricoService();
        private UsuarioRolService usuarioRolService = new UsuarioRolService();
        private DenunciaCorreoAnonimoService denunciaCorreoAnonimoService = new DenunciaCorreoAnonimoService();
        private DenunciaOficialCumplimientoService denunciaOficialCumplimientoService = new DenunciaOficialCumplimientoService();
        private static string rutaArchivos = "~/Archivos/D_";

        // GET: Denuncia
        [HttpGet]
        public ActionResult Index()
        {
            List<DenunciaListOutputDto> denunciaListOutputDtos = new List<DenunciaListOutputDto>();
            string idUsuario = "";
            try
            {

                sesionUsuario = (SesionUsuarioDto)Session["SesionActiva"];

                //if (sesionUsuario.IdRol.ToString() != "1")
                //{
                    idUsuario = sesionUsuario.UsuarioId.ToString();
                //}
                

                var result = denunciaService.SelectList(util.UrlServicios, sesionUsuario.Token, "", "", "", "", "", "", "", "", "", idUsuario, sesionUsuario.IdRol.ToString());

                if (result != null)
                {
                    if (result.Respuesta.CodigoRetorno == 1)
                    {
                        sesionUsuario.Token = result.Respuesta.Token;
                        if (result.Resultado.Data.Count > 0)
                        {
                            foreach (var item in result.Resultado.Data)
                            {
                                var resultDenuncia = JsonConvert.DeserializeObject<DenunciaListOutputDto>(item.ToString());
                                denunciaListOutputDtos.Add(resultDenuncia);
                            }
                        }
                    }
                }

                /* Combobox  */
                ViewBag.Perfil = sesionUsuario.IdRol.ToString();
                ViewBag.Denuncia = "";
                ViewBag.FechaIngreso = "";
                ViewBag.FechaOcurrencia = "";
                ViewBag.Sede = new SelectList(combobox.ComboboxSede(sesionUsuario.Token), "IdSede", "Descripcion", 0);
                ViewBag.TipoDelito = new SelectList(combobox.ComboboxTipoDelito(sesionUsuario.Token), "IdTipoDelito", "Nombre", 0);
                ViewBag.Estado = new SelectList(combobox.ComboboxEstado(sesionUsuario.Token), "IdEstadoDenuncia", "Nombre", 0);
                ViewBag.IdSede = 0;
                ViewBag.IdEstado = 0;
                ViewBag.IdTipoDelito = 0;
                ViewBag.IdUsuario = sesionUsuario.UsuarioId;
                ViewBag.RolDenunciante = util.RolDenunciante;
                ViewBag.RolComite = util.RolComiteEtica;
                ViewBag.RolOficial = util.RolOficialCumplimiento;

            }
            catch (Exception ex)
            {
                return Json(util.RespuestaJson(false, ModelState, ex.Message, ""), JsonRequestBehavior.AllowGet);
            }
            return View("Index", denunciaListOutputDtos);
        }
        // GET: Denuncia/IndexFiltro
        [HttpGet]
        public ActionResult IndexFiltro(string Denuncia, string FechaDenuncia, string FechaOcurrencia, string IdSede, string IdDepartamento, string IdTipoDelito, string IdEstado)
        {
            List<DenunciaListOutputDto> denunciaListOutputDtos = new List<DenunciaListOutputDto>();
            string idUsuario = "";
            try
            {
                /*======================================== Session y Perfilamiento ========================================*/
                //if (CheckPermiso() == 0)
                //{
                //    return RedirectToAction("Error403", "Error");
                //}
                /*===========================================================================================================*/

                sesionUsuario = (SesionUsuarioDto)Session["SesionActiva"];
                string inicioDenuncia = "", finDenuncia = "", inicioOcurrencia = "", finOcurrencia = "";
                if (FechaDenuncia != null)
                {
                    if (FechaDenuncia.Length > 0)
                    {
                        string[] fechas = FechaDenuncia.Split('-');
                        inicioDenuncia = util.FechaToIso(fechas[0].ToString().Trim());
                        finDenuncia = util.FechaToIso(fechas[1].ToString().Trim());
                    }
                }

                if (FechaOcurrencia != null)
                {
                    if (FechaOcurrencia.Length > 0)
                    {
                        string[] fechas = FechaOcurrencia.Split('-');
                        inicioOcurrencia = util.FechaToIso(fechas[0].ToString().Trim());
                        finOcurrencia = util.FechaToIso(fechas[1].ToString().Trim());
                    }
                }

                if (sesionUsuario.IdRol.ToString() == "3")
                {
                    idUsuario = sesionUsuario.IdRol.ToString();
                }

                var result = denunciaService.SelectList(util.UrlServicios, sesionUsuario.Token, Denuncia, inicioDenuncia, finDenuncia, inicioOcurrencia, finOcurrencia, IdSede, IdDepartamento, IdTipoDelito, IdEstado, idUsuario);

                if (result != null)
                {
                    if (result.Respuesta.CodigoRetorno == 1)
                    {
                        sesionUsuario.Token = result.Respuesta.Token;
                        if (result.Resultado.Data.Count > 0)
                        {
                            foreach (var item in result.Resultado.Data)
                            {
                                var resultDenuncia = JsonConvert.DeserializeObject<DenunciaListOutputDto>(item.ToString());
                                denunciaListOutputDtos.Add(resultDenuncia);
                            }
                        }
                    }
                }


                /*
              * Combobox
              */
                ViewBag.Sede = new SelectList(combobox.ComboboxSede(sesionUsuario.Token), "IdSede", "Descripcion", IdSede);
                if (IdSede.Length > 0)
                {
                    if (IdSede != "0")
                    {
                        ViewBag.Departamento = new SelectList(combobox.ComboboxDepartamento(sesionUsuario.Token, 1, Convert.ToInt32(IdSede)), "IdDepartamento", "Nombre", IdDepartamento);
                    }
                }

                ViewBag.Denuncia = Denuncia;
                ViewBag.FechaIngreso = FechaDenuncia;
                ViewBag.FechaOcurrencia = FechaOcurrencia;
                ViewBag.TipoDelito = new SelectList(combobox.ComboboxTipoDelito(sesionUsuario.Token), "IdTipoDelito", "Nombre", IdTipoDelito);
                ViewBag.Estado = new SelectList(combobox.ComboboxEstado(sesionUsuario.Token), "IdEstadoDenuncia", "Nombre", IdEstado);
                ViewBag.IdSede = IdSede;
                ViewBag.IdTipoDelito = IdTipoDelito;
                ViewBag.IdEstado = IdEstado;
                ViewBag.IdUsuario = sesionUsuario.UsuarioId;
                ViewBag.Error = 0;
                ViewBag.Perfil = sesionUsuario.IdRol.ToString();
                ViewBag.RolDenunciante = util.RolDenunciante;
                ViewBag.Comite = util.RolComiteEtica;
                ViewBag.Oficial = util.RolOficialCumplimiento;

                return View("Index", denunciaListOutputDtos);

            }
            catch
            {

Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Views/Denuncia/DatosAdjuntos.cshtml
<div class="row">
    <div class="col-md-12 col-sm-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Denuncia</li>
            </ol>
        </nav>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="~/denuncia/DatosInvolucrados?idDenuncia=@ViewBag.IdDenuncia">Involucrados</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active">Documentos Adjuntos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/denuncia/datosDetalles?idDenuncia=@ViewBag.IdDenuncia">Detalle</a>
            </li>
            @if (ViewBag.Perfil == ViewBag.RolOficial)
            {
                <li class="nav-item">
                    <a class="nav-link" href="~/denuncia/datosEstado?idDenuncia=@ViewBag.IdDenuncia">Estado</a>
                </li>
            }
           
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("GuardarAdjuntos", "Denuncia", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="card">
                <div class="card-header text-white maru_card_info">
                    Documentos adjuntos
                </div>
                <div class="card-body">

                    <div class="mb-3">
                        @Html.TextBox("file", "", new { @class = "form-control", @type = "file" }) <br />
                    </div>
                    <div class="mb-3">
                        @Html.TextBox("file1", "", new { type = "file", @class = "form-control" }) <br />
                    </div>
                    <div class="mb-3">
                        @Html.TextBox("file2", "", new { type = "file", @class = "form-control" }) <br />
                    </div>
                    <div class="mb-3">
                        @Html.TextBox("file3", "", new { type = "file", @class = "form-control" }) <br />
                    </div>
                    <div class="mb-3">
                        @Html.TextBox("file4", "", new { type = "file", @class = "form-control" }) <br />
                    </div>
                    <div class="float-end">
                        <input type="submit" value="Upload" class="btn btn-primary btn-sm" title="Cargar Archivos" />
                    </div>

                    @*<div>
                        <input type="submit" value="Upload" />
                    </div>*@

                    <input type="hidden" id="IdDenuncia" name="IdDenuncia" value="@ViewBag.IdDenuncia" />

                    
                </div>
                <div class="card-footer">
                    <a href="~/denuncia/Cancelar" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Cancelar Ingreso"><i class="fas fa-ban"></i>&nbsp;Cancelar</a>
                    @if (ViewBag.Modificar == 0)
                    {
                        <div class="float-end">
                            <input type="submit" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="bottom" title="Continuar" />
                            @*<a id="btnContinuar" name="btnContinuar" href="#" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="bottom" title="Continuar"><i class="fas fa-chevron-circle-right"></i>&nbsp;Continuar</a>*@
                        </div>
                    }
                </div>
            </div>
        }
        </div>
    </div>

    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Assets/DataTables/datatables.js"></script>
    <script src="~/Assets/Datetimepicker/js/moment.min.js"></script>
    <script src="~/Assets/Datetimepicker/js/daterangepicker.js"></script>
    <script src="~/Scripts/sweetalert2.all.min.js"></script>
    <script src="~/Scripts/page/datosAdjuntos.js"></script>
    <script>
       
    </script>

Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Views/Denuncia/DatosArchivosAdjuntos.cshtml
@model List<string>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="~/denuncia/Cancelar">Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">Denuncia</li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link" href="~/denuncia/DatosInvolucrados?idDenuncia=@ViewBag.IdDenuncia">Involucrados</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active">Documentos Adjuntos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="~/denuncia/datosDetalles?idDenuncia=@ViewBag.IdDenuncia">Detalle</a>
            </li>
            @if (ViewBag.VerEstado == 1)
            {
                <li class="nav-item">
                    <a class="nav-link" href="~/denuncia/datosEstado?idDenuncia=@ViewBag.IdDenuncia">Estado</a>
                </li>
            }
           
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-12">
       
        <div class="card">
            @using (Html.BeginForm("GuardarArchivosAdjuntos", "Denuncia", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <div class="card-body">

                <div class="mb-3">
                    @Html.TextBox("file", "", new { @class = "form-control", @type = "file", @accept = ".doc,.docx, .pdf, .xls,.xlsx, .ppt, .pptx, .jpeg" }) <br />
                </div>
                @if (ViewBag.Cantidad < 5)
                {
                    if (ViewBag.Modificar == 0)
                    {
                        <div class="float-end">
                            <input type="submit" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="bottom" title="Guardar" value="Guardar Archivo" />

                        </div>
                    }
                }
                @Html.AntiForgeryToken()
            </div>
            }
            <div class="card-body">
                <div class="card">
                    <div class="card-header">Documentos Adjuntos Peso (@ViewBag.Peso /20 MB)</div>

                    <div class="card-body maru_card_sinBorde">
                        <table id="tblResultado" class="table table-bordered table-condensed table-hover tabla_condensada">
                            <thead>
                                <tr>
                                    <th>Nombre </th>
                                    <th style="width:100px; text-align:center;">Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (string item in Model)
                                {
                                    <tr>
                                        <td>@item</td>
                                        <td style="text-align:center;">
                                            <a id="btnDescargar" name="btnDescargar" class="btnGrilla" href="#" onclick="Descargar('@item');" data-toggle="tooltip" data-placement="top" title="Descargar"><i class="fas fa-lg fa-download" style="color:green"></i></a>
                                            @if (ViewBag.Modificar == 0)
                                            {
                                            <a id="btnEliminar" name="btnEliminar" class="btnGrilla" href="#" onclick="Eliminar('@item');" data-toggle="tooltip" data-placement="top" title="Eliminar"><i class="fas fa-lg fa-trash"></i></a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

                <input type="hidden" id="IdDenuncia" name="IdDenuncia" value="@ViewBag.IdDenuncia" />
                
            </div>
            <div class="card-footer">
                <a href="~/denuncia/Cancelar" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Cancelar Ingreso"><i class="fas fa-ban"></i>&nbsp;Cancelar</a>
                @if (ViewBag.Modificar == 0)
                {
                    <div class="float-end">
                        <a id="btnContinuar" name="btnContinuar" href="~/denuncia/datosdetalles?idDenuncia=@ViewBag.IdDenuncia" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="bottom" title="Continuar"><i class="fas fa-chevron-circle-right"></i>&nbsp;Continuar</a>
                    </div>
                }
            </div>
        </div>
        
        </div>
    </div>

    <script src="~/Scripts/jquery-3.5.1.js"></script>
    <script src="~/Scripts/umd/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Assets/DataTables/datatables.js"></script>
    <script src="~/Assets/Datetimepicker/js/moment.min.js"></script>
    <script src="~/Assets/Datetimepicker/js/daterangepicker.js"></script>
    <script src="~/Scripts/sweetalert2.all.min.js"></script>
    <script src="~/Scripts/page/datosAdjuntos.js"></script>
    <script>
       
    </script>

Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Views/Denuncia/NoRegistra.cshtml
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">                       
                    </div>
                    <div class="card-body">
                        <div class="form-row">
                            <p>
                                Hemos recibido su denuncia con éxito, sin embargo usted a incluido en su denuncia a todos los miembros del comité de ética, lo que hace imposible revisar su denuncia en Chile, por este motivo le solicitamos que ingresé su denuncia directamente en el canal de ética de Japón, </p>
                            <p>
                                para ello por favor haga su denuncia en el siguiente link
                            </p>
                            <p>
                                <a href="https://www.marubenicorp.ethicspoint.com"> www.marubenicorp.ethicspoint.com </a>
                            </p>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       
    </div>
    <div class="card-footer">
        <a href="~/denuncia/Cancelar" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Cancelar Ingreso"><i class="fas fa-ban"></i>&nbsp;Cancelar</a>
        <div class="float-end">
            @*<a id="btnImprimir" name="btnImprimir" href="#" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Imprimir"><i class="fas fa-print"></i>&nbsp;Imprimir</a>*@
        </div>        
    </div>
</div>

<script src="~/Scripts/popper.min.js"></script>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Assets/DataTables/datatables.js"></script>
<script src="~/Assets/Datetimepicker/js/moment.min.js"></script>
<script src="~/Assets/Datetimepicker/js/daterangepicker.js"></script>
<script>
     $("#btnImprimir").click(function () {
        window.open("@Url.Action("NoRegistra","Denuncia")", "_blank",
            "menubar=no, toolbar=no, resizable=no, top=100, left=200, width=900, height=500");
    });
</script>

Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Views/Denuncia/Resumen.cshtml
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        Información de la Denuncia
                    </div>
                    <div class="card-body">
                        <div class="form-row">
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Identificador Denuncia</label>
                                <p><strong>@Model.Identificador</strong></p>
                            </div>
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Fecha Inicio Ocurrencia</label>
                                <p><strong>@Model.detalles.FechaInicio</strong></p>
                            </div>
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Fecha Fin Ocurrencia</label>
                                <p><strong>@Model.detalles.FechaFin</strong></p>
                            </div>
                            <div class="form-group col-md-3 col-sm-12">
                                <label>Observación</label>
                                <p><strong>@Model.detalles.Comentario</strong></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
                        Involucrados
                    </div>
                    <div class="card-body">
                        <table id="tblResultado" class="table table-bordered table-condensed table-hover tabla_condensada">
                            <thead>
                                <tr>
                                    <th style="width:200px; text-align:center;">Nombre</th>
                                    <th style="width:150px; text-align:center;">Sede</th>
                                    <th style="text-align:center;">Departamento</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    if (Model.involucrados != null)
                                    {
                                        foreach (var item in Model.involucrados)
                                        {
                                            <tr>
                                                <td>@item.nombre</td>
                                                <td>@item.sede</td>
                                                <td>@item.departamento</td>
                                            </tr>
                                        }
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <a href="~/denuncia/Cancelar" class="btn btn-sm btn-danger" data-toggle="tooltip" data-placement="bottom" title="Cancelar Ingreso"><i class="fas fa-ban"></i>&nbsp;Cancelar</a>
        <div class="float-end">
            <a id="btnImprimir" name="btnImprimir" href="#" class="btn btn-primary btn-sm" data-toggle="tooltip" data-placement="top" title="Imprimir"><i class="fas fa-print"></i>&nbsp;Imprimir</a>
        </div>        
    </div>
</div>

<script src="~/Scripts/popper.min.js"></script>
<script src="~/Scripts/jquery-3.5.1.js"></script>
<script src="~/Scripts/bootstrap.js"></script>
<script src="~/Assets/DataTables/datatables.js"></script>
<script src="~/Assets/Datetimepicker/js/moment.min.js"></script>
<script src="~/Assets/Datetimepicker/js/daterangepicker.js"></script>
<script>
     $("#btnImprimir").click(function () {
        window.open("@Url.Action("ResumenDenuncia","Denuncia")", "_blank",
            "menubar=no, toolbar=no, resizable=no, top=100, left=200, width=900, height=500");
    });
</script>

Web/MHOL-CANALDENUNCIA-2.0/CanalDenunciaWeb/Views/Denuncia/vmObservacion.cshtml
 @model CanalDenunciaWeb.Data.Package.DenunciaComentarioPkg.DenunciaComentarioOutputDto
<div class="card">
    <div class="card-header">Detalle Observación</div>
    <div class="card-body">
        <label id="lblObs">@Model.Comentario</label>
    </div>
    <div class="card-footer">
        <div class="float-end">
            <a id="btnCancelar" name="btnCancelar" href="~/denuncia/datosDetalles?idDenuncia=@Model.IdDenuncia" class="btn btn-success btn-sm" data-toggle="tooltip" data-placement="bottom" title="Cancelar"><i class="fas fa-chevron-circle-right"></i>&nbsp;Cancelar</a>
        </div>
    </div>
</div>